#!/usr/bin/perl

use warnings;
use strict;
use 5.12.0;

use Getopt::Long;

my $user;
my $pass;
my $group = 'sftp-only';
my $home;
my $name;
my $shell = '/sbin/nologin';
my $data  = 'data';

my $args = GetOptions (
                    "user|u=s"  => \$user,
                    "pass|p=s"  => \$pass,
                    "group|g=s" => \$group,
                    "home|h=s"  => \$home,
                    "name|n=s"  => \$name,
                    "shell|s=s" => \$shell,
                    "data|d=s"  => \$data,
            );

# check if user exists

if ( ! $user ) {
    print "\n\nUser not specified... exiting.\n\n";
    exit;
}

if ( defined( getpwnam( $user ))) {
    print "\n\nUser $user already exists... exiting.\n\n";
    exit;
}

# let's check for args

# user's real name... if not supplied, we'll show that

$name = "not supplied" if ! $name;

# home directory

if ( ! $home ) {
    $home = home_dir();
}

# random pass if not supplied on cli

if ( ! $pass ) {
    $pass = random_pass();
}

# add the user

system( "echo $pass | pw useradd -n $user -c '$name' -s $shell -g $group -h 0 -d $data -m" );

print "\n\nUser $user created. Note their password: $pass\n\n";

# create and own the chroot 

dir_create( $user, $home, $data );

sub random_pass {

    my @valid;
    push @valid, qw( a A b B c C d D e E f F g G h H k K m );
    push @valid, qw( M n N p P r R s S t T w W x X y Y z Z );
    push @valid, qw( 2 3 4 5 6 7 8 9 * ? ! % $ );

    my $length = 8;
    my $pass;

    for ( 1..$length) {
        $pass .= $valid[ int( rand( @valid )) ];
    }
    return $pass;
}
sub home_dir {

    $home = "/usr/home/$user";
    return $home;
}
sub dir_create {
    
    my ( $user, $home, $data ) = @_;

    my ( $uid, $gid ) = ( getpwnam( $user ) )[ 2,3 ];

    mkdir "$home";
    chown 0, $gid, $home;

    mkdir "$home/$data";
    chown $uid, $gid, "$home/$data";

    unlink "$home/.*";
}
