#!/usr/bin/perl

use warnings;
use strict;
use 5.12.0;

use Getopt::Long;

my $user;
my $pass;
my $group = "sftp-only";
my $home;

my $args = GetOptions (
                    "user|u=s"  => \$user,
                    "pass|p=s"  => \$pass,
                    "group|g=s" => \$group,
                    "home|h=s"  => \$home,
                );

# check if user exists

if ( defined( getpwnam( $user ))) {
    print "\n\nUser $user already exists... exiting.\n\n";
    exit;
}

# check if user wants random pass, and assign random if not

if ( ! $pass ) {
    $pass = random_pass();
}

sub random_pass {

    my @valid;
    push @valid, qw( a A b B c C d D e E f F g G h H k K m );
    push @valid, qw( M n N p P r R s S t T w W x X y Y z Z );
    push @valid, qw( 2 3 4 5 6 7 8 9 );

    my $length = 8;
    my $pass;

    for ( 1..$length) {
        $pass .= $valid[ int( rand( @valid )) ];
    }
}
